### ISSUE TITLE
support to macos arm64

### ISSUE THREAD

**Issue by MOHD-MS** [virtualroot/asdf-opentofu#5] opened 2023-10-05 05:55 UTC
**Describe the bug**

~ asdf install opentofu latest                                                                                    
redirect url: https://github.com/opentofu/opentofu/releases/tag/v1.6.0-alpha1
Downloading opentofu release v1.6.0-alpha1...
opentofu 1.6.0-alpha1 installation was successful!
~ asdf global opentofu latest                                                                                      
redirect url: https://github.com/opentofu/opentofu/releases/tag/v1.6.0-alpha1
~ tofu                                                                                                              
zsh: command not found: tofu
~ tofu --version                                                                                                 
zsh: command not found: tofu

**Steps to reproduce**

# Install plugin
asdf plugin add opentofu https://github.com/virtualroot/asdf-opentofu.git

# Show all installable versions
asdf list-all opentofu

# Install specific version
asdf install opentofu latest

# Set a version globally (on your ~/.tool-versions file)
asdf global opentofu latest

# Now opentofu commands are available
tofu --version

how to fix this issue in macos arm64

**Comment by virtualroot** [comment] 2023-10-05 13:45
@MOHD-MS I tried it on Apple silicon and I can't reproduce it.

Try running `asdf reshim` and then `tofu`.

If that doesn't work:
- What do you see inside the `./.asdf/installs/opentofu` folder?
- Does it works if you run the binary like `./.asdf/installs/opentofu/1.6.0-alpha1/bin/tofu version`? What is the output? 
- What is the output of `file ~/.asdf/installs/opentofu/1.6.0-alpha1/bin/tofu`

About asdf:
- which version of `asdf` are you running? `asdf version`
- Was it installed with git or homebrew?

**Comment by eliecharra** [comment] 2023-10-06 10:29
It seems to be an issue with your asdf setup. 
I just tried locally on a M2 and it works like a charm.

**Comment by MOHD-MS** [comment] 2023-10-06 10:43
this works now, after asdf reshim it fixed, what was the issue

**Comment by virtualroot** [comment] 2023-10-11 09:21
I'm closing this issue as it seems it was a one-off problem.

**Closed by virtualroot** 2023-10-11 09:21 UTC
Labels: bug
